import os
import sys
import requests
from datetime import datetime, timezone


SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")


def fail(message):
    print(f"ERROR: {message}")
    sys.exit(1)


if not SUPABASE_URL:
    fail("SUPABASE_URL is missing")

if not SUPABASE_KEY:
    fail("SUPABASE_SERVICE_ROLE_KEY is missing")


HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "resolution=merge-duplicates",
}


def supabase_upsert(table, rows):
    if not rows:
        print(f"{table}: nothing to sync")
        return

    url = f"{SUPABASE_URL}/rest/v1/{table}"

    response = requests.post(
        url,
        headers=HEADERS,
        params={"on_conflict": "external_id"},
        json=rows,
        timeout=30,
    )

    if not response.ok:
        print(response.text)
        fail(f"Supabase returned HTTP {response.status_code}")

    print(f"{table}: synced {len(rows)} rows")


def normalize_match(match):
    """
    Convert a football match object into our Supabase matches schema.

    This accepts common field names so the script is easier to connect
    to different football APIs later.
    """

    external_id = (
        match.get("external_id")
        or match.get("id")
        or match.get("match_id")
        or match.get("event_id")
    )

    home_team = (
        match.get("home_team")
        or match.get("homeTeam")
        or match.get("home")
        or "Unknown"
    )

    away_team = (
        match.get("away_team")
        or match.get("awayTeam")
        or match.get("away")
        or "Unknown"
    )

    kickoff = (
        match.get("kickoff_at")
        or match.get("kickoff")
        or match.get("date")
        or match.get("datetime")
    )

    if not external_id:
        return None

    if not kickoff:
        return None

    status = match.get("status", "scheduled")

    status_map = {
        "NS": "scheduled",
        "TBD": "scheduled",
        "SCHEDULED": "scheduled",
        "LIVE": "live",
        "IN_PLAY": "live",
        "FT": "finished",
        "FINISHED": "finished",
        "POSTPONED": "postponed",
        "CANCELLED": "cancelled",
    }

    status = status_map.get(str(status).upper(), status)

    if status not in {
        "scheduled",
        "live",
        "finished",
        "postponed",
        "cancelled",
    }:
        status = "scheduled"

    home_score = (
        match.get("home_score")
        or match.get("homeScore")
    )

    away_score = (
        match.get("away_score")
        or match.get("awayScore")
    )

    return {
        "external_id": str(external_id),

        "home_team": str(home_team),
        "away_team": str(away_team),

        "home_team_id": (
            str(match["home_team_id"])
            if match.get("home_team_id") is not None
            else None
        ),

        "away_team_id": (
            str(match["away_team_id"])
            if match.get("away_team_id") is not None
            else None
        ),

        "competition": (
            match.get("competition")
            or match.get("league")
        ),

        "kickoff_at": kickoff,

        "venue": match.get("venue"),

        "status": status,

        "home_score": home_score,
        "away_score": away_score,

        "prediction_locked": status in {
            "live",
            "finished",
            "cancelled",
        },

        "source": match.get("source", "football-pipeline"),

        "updated_at": datetime.now(timezone.utc).isoformat(),
    }


def load_matches():
    """
    Try to load matches from files generated by the existing pipeline.

    We intentionally support several possible JSON locations.
    """

    import json
    from pathlib import Path

    possible_files = [
        Path("matches.json"),
        Path("data/matches.json"),
        Path("docs/matches.json"),
        Path("matches/matches.json"),
    ]

    for path in possible_files:
        if path.exists():
            print(f"Loading matches from {path}")

            with path.open("r", encoding="utf-8") as f:
                data = json.load(f)

            if isinstance(data, dict):
                data = (
                    data.get("matches")
                    or data.get("events")
                    or data.get("data")
                    or []
                )

            if not isinstance(data, list):
                fail(f"{path} does not contain a match list")

            return data

    print("No matches JSON file found.")
    return []


def main():

    print("====================================")
    print("FOOTBALL PIPELINE → SUPABASE")
    print("====================================")

    matches = load_matches()

    normalized = []

    for match in matches:
        item = normalize_match(match)

        if item:
            normalized.append(item)

    print(f"Found {len(normalized)} valid matches")

    supabase_upsert(
        "matches",
        normalized
    )

    print("Supabase synchronization completed.")


if __name__ == "__main__":
    main()
